create annoucement functionality
ZPI-UKW/zpi-back-end pull request #7
Opened 2021-05-27 22:10 UTC by lzawistowsky

2021-05-28 16:02 UTC, zawolanski requested changes
Overall fine, but there are a few things you need to fix.

I hope that you remember about fields validation.

2021-05-28 16:02 UTC, zawolanski commented on graphql/resolvers/annoucement.js
> +        const error = new Error('Invalid user')
Invalid error message.

2021-05-28 16:02 UTC, zawolanski commented on graphql/resolvers/annoucement.js
> +    if(!user) {
You should check if user who wants to create new annoucement is logged in using code like below:
```
if (!isAuth && !userId) {
    const error = new Error('Not authorized');
    error.code = 401;
    throw error;
  }
```
Then you should pass `userId` extracted from token in `auth` middleware to `findOne` (or `findById`) method.

2021-05-28 16:02 UTC, zawolanski commented on graphql/schema/annoucement.js
> +        category: ID!
I think that every field except `images` should be required.

2021-05-28 16:02 UTC, zawolanski commented on graphql/resolvers/annoucement.js
> +    console.log(annoucement)
This `console.log` is unnecessary.

2021-06-02 10:13 UTC, zawolanski approved these changes

2021-06-04 11:31 UTC, pawelsobkowski approved these changes

2021-06-07 18:53 UTC, merged